CREATE TABLE REGISTRO(
CEDULA VARCHAR(12) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(40) NOT NULL,
APELLIDO VARCHAR(40) NOT NULL,
TELEFONO VARCHAR(10) NOT NULL,
DIRECCION VARCHAR(90) NOT NULL,
GENERO VARCHAR (1) NOT NULL,
ECIVIL VARCHAR (1) NOT NULL,
HIJOS VARCHAR (1) NOT NULL,
CELULAR VARCHAR(10),
F_NACIMIENTO DATE);



--Nueva tabla
--hmiembro es por si se hizo miembro de la iglesia
--si fue bautizado en la iglesia, entonces es miembro desde siempre
--bautizadoe es por el bautismo del espiritu santo


CREATE TABLE IGLESIA(
IDIGLESIA VARCHAR(12) foreign key (IDIGLESIA)
references REGISTRO(CEDULA) On Update Cascade On Delete Cascade,
FCONVERSION date NOT NULL,
FBAUTISMO date NOT NULL,
BAUTIZADOE VARCHAR(2) NOT NULL,
H_MIEBRO VARCHAR(2) NOT NULL,
FMIEMBRO date NOT NULL,
CONGREGACION VARCHAR (90) NOT NULL);


--Modificar tabla y valores
--ALTER TABLE REGISTRO ALTER COLUMN PRIMARY KEY CEDULA VARCHAR (12)

--Store Procedure Registro

CREATE PROC SP_REGISTRO
@CEDULA VARCHAR(12),
@NOMBRE VARCHAR(40),
@APELLIDO VARCHAR(40),
@TELEFONO VARCHAR(10),
@DIRECCION VARCHAR(90),
@GENERO VARCHAR (1),
@ECIVIL VARCHAR (1),
@HIJOS VARCHAR (1),
@CELULAR VARCHAR(10),
@F_NACIMIENTO DATE
AS
BEGIN
INSERT INTO REGISTRO
                         (CEDULA, NOMBRE, APELLIDO, TELEFONO, DIRECCION, GENERO, ECIVIL, HIJOS, CELULAR, F_NACIMIENTO)
VALUES        (@CEDULA,@NOMBRE,@APELLIDO,@TELEFONO,@DIRECCION,@GENERO,@ECIVIL,@HIJOS,@CELULAR,@F_NACIMIENTO)

END

GO

--Store Procedure Iglesia

CREATE PROC SP_INGRESARIGLESIA

@IDIGLESIA VARCHAR(12),
@FCONVERSION date,
@FBAUTISMO date,
@BAUTIZADOE VARCHAR(2),
@H_MIEBRO VARCHAR(2),
@FMIEMBRO date,
@CONGREGACION VARCHAR (90)

AS
BEGIN
INSERT INTO IGLESIA
                         (IDIGLESIA, FCONVERSION, FBAUTISMO, BAUTIZADOE, H_MIEBRO, FMIEMBRO, CONGREGACION)
VALUES        (@IDIGLESIA,@FCONVERSION,@FBAUTISMO,@BAUTIZADOE,@H_MIEBRO,@FMIEMBRO,@CONGREGACION)

END
GO

--SP Buscar
CREATE PROC Buscar
AS
BEGIN
SELECT        REGISTRO.NOMBRE, REGISTRO.APELLIDO, REGISTRO.CEDULA, REGISTRO.TELEFONO, REGISTRO.GENERO, REGISTRO.ECIVIL, IGLESIA.FMIEMBRO, IGLESIA.FBAUTISMO, IGLESIA.CONGREGACION
FROM            IGLESIA INNER JOIN
                         REGISTRO ON IGLESIA.IDIGLESIA = REGISTRO.CEDULA

END

--Este storeprocedure es utilizado para buscar por parametro en el formulario buscar

CREATE PROC SP_BUSCARLIKE
AS @NOMBRE VARCHAR(40)
AS
BEGIN
SELECT        REGISTRO.NOMBRE, REGISTRO.APELLIDO, REGISTRO.CEDULA, REGISTRO.TELEFONO, REGISTRO.GENERO, REGISTRO.ECIVIL, IGLESIA.FMIEMBRO, IGLESIA.FBAUTISMO, IGLESIA.CONGREGACION
FROM            IGLESIA INNER JOIN
                         REGISTRO ON IGLESIA.IDIGLESIA = REGISTRO.CEDULA

WHERE NOMBRE LIKE '%'+@NOMBRE+'%'
END

EXEC SP_BUSCARLIKE

--Este storeprocedure es utilizado para jalar la cedula y modificarla dentro de la lista

CREATE PROC SP_BUSCARLIKEID
@CEDULA VARCHAR(12)
AS
BEGIN
SELECT        REGISTRO.CEDULA, REGISTRO.NOMBRE, REGISTRO.APELLIDO, REGISTRO.TELEFONO, REGISTRO.DIRECCION, REGISTRO.GENERO, REGISTRO.ECIVIL, REGISTRO.HIJOS, REGISTRO.CELULAR, REGISTRO.F_NACIMIENTO, 
                         IGLESIA.FCONVERSION, IGLESIA.FBAUTISMO, IGLESIA.BAUTIZADOE, IGLESIA.H_MIEBRO, IGLESIA.FMIEMBRO, IGLESIA.CONGREGACION
FROM            IGLESIA INNER JOIN
                         REGISTRO ON IGLESIA.IDIGLESIA = REGISTRO.CEDULA
WHERE CEDULA = @CEDULA
END

--STORE PROCEDURE PARA ACTUALIZAR

CREATE PROC SP_ACTUALIZARREGISTRO

@CEDULA VARCHAR(12),
@NOMBRE VARCHAR(40),
@APELLIDO VARCHAR(40),
@TELEFONO VARCHAR(10),
@DIRECCION VARCHAR(90),
@GENERO VARCHAR (1),
@ECIVIL VARCHAR (1),
@HIJOS VARCHAR (1),
@CELULAR VARCHAR(10),
@F_NACIMIENTO DATE

AS
BEGIN
     UPDATE       REGISTRO
SET                CEDULA = @CEDULA, NOMBRE = @NOMBRE, APELLIDO = @APELLIDO, TELEFONO = @TELEFONO, DIRECCION = @DIRECCION, GENERO = @GENERO, ECIVIL = @ECIVIL, HIJOS = @HIJOS, CELULAR = @CELULAR, 
                         F_NACIMIENTO = @F_NACIMIENTO  
END



CREATE PROC SP_ACTUALIZARIGLESIA

@IDIGLESIA VARCHAR(12),
@FCONVERSION date,
@FBAUTISMO date,
@BAUTIZADOE VARCHAR(2),
@H_MIEBRO VARCHAR(2),
@FMIEMBRO date,
@CONGREGACION VARCHAR (90)

AS
BEGIN
UPDATE       IGLESIA
SET                FCONVERSION = @FCONVERSION, FBAUTISMO = @FBAUTISMO, BAUTIZADOE = @BAUTIZADOE, H_MIEBRO = @H_MIEBRO, FMIEMBRO = @FMIEMBRO, CONGREGACION = @CONGREGACION
END